name: download and collate dam data

#when it should run
on:
  schedule:
    - cron: "0 12 * * *" #run everyday at utc 12

#create jobs    
jobs:
  dam: 
    runs-on: windows-latest
    
    steps: 

    # load repo
    - uses: actions/checkout@main

    # setup r
    - uses: r-lib/actions/setup-r@master

    # install packages
    - name: Install packages
      run: |
        install.packages("tidyverse")
        install.packages("httr")
        install.packages("lubridate")
      shell: Rscript {0}

    - name: Download and collate dam data
      run: |
        source('setup_and_source.R')
      shell: Rscript {0}
      
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/*
        git commit -am "gh action dam download $(date)"
        git push origin main
